version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks: 
      - backend
  backend:
    container_name: base_api
    depends_on:
      - mysql
    build: .
    restart: always
    ports:
      - 8181:8181
    networks: 
      - backend
    command: npm run start:prod
  migration:
    build:
      context: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "mysql:3306",
        "--",
        "npm",
        "run",
        "migration:run"
      ]
    links:
      - mysql
    depends_on:
      - mysql
    env_file: ./.env
    environment:
      - DB_HOST=mysql
    networks: 
      - backend


volumes:
  dbdata:

networks:
  backend:
    driver: bridge